--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAL
--------------------------------------------------------

  CREATE TABLE "ARIMOATESTDB"."CAL" 
   (	"IDX" NUMBER(20,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"STARTDATE" TIMESTAMP (6) DEFAULT SYSDate, 
	"CATECODE" NUMBER(10,0) DEFAULT 0, 
	"LEADER_ID" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into ARIMOATESTDB.CAL
SET DEFINE OFF;
Insert into ARIMOATESTDB.CAL (IDX,TITLE,STARTDATE,CATECODE,LEADER_ID) values (1,'쿠크갈사람',to_timestamp('22/02/28 14:37:51.000000000','RR/MM/DD HH24:MI:SSXFF'),0,'관리자');
Insert into ARIMOATESTDB.CAL (IDX,TITLE,STARTDATE,CATECODE,LEADER_ID) values (2,'쿠크갈사람2',to_timestamp('22/02/28 15:05:28.000000000','RR/MM/DD HH24:MI:SSXFF'),2,'관리자');
Insert into ARIMOATESTDB.CAL (IDX,TITLE,STARTDATE,CATECODE,LEADER_ID) values (3,'쿠크갈사람2',to_timestamp('22/02/28 15:05:31.000000000','RR/MM/DD HH24:MI:SSXFF'),3,'관리자');
--------------------------------------------------------
--  DDL for Index SYS_C0023313
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIMOATESTDB"."SYS_C0023313" ON "ARIMOATESTDB"."CAL" ("IDX") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CAL
--------------------------------------------------------

  ALTER TABLE "ARIMOATESTDB"."CAL" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
