--------------------------------------------------------
--  파일이 생성됨 - 월요일-3월-07-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CATEGORI_JH
--------------------------------------------------------

  CREATE TABLE "ARIMOATESTDB"."CATEGORI_JH" 
   (	"CATENAME" VARCHAR2(20 BYTE), 
	"CATECODE" VARCHAR2(30 BYTE), 
	"CATECODEREF" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "ARIMOATESTDB"."CATEGORI_JH"  IS 'categori_jh				
컬럼명	자료형	null	제약조건	용도
catename	varchar2(30)	not null		카테고리 이름
catecode	varchar2(30)	not null	pk	board 게시판의 catecode 와 연동
catecoderef	varchar2(30)		FK,references catecode	게싯글 내용
';
REM INSERTING into ARIMOATESTDB.CATEGORI_JH
SET DEFINE OFF;
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('공지사항','100',null);
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('필독','101','100');
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('긴급이슈','102','100');
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('일반','200',null);
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('자유','201','200');
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('파일','202','200');
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('카테고리 없음','0',null);
Insert into ARIMOATESTDB.CATEGORI_JH (CATENAME,CATECODE,CATECODEREF) values ('카테고리 없음','00','0');
--------------------------------------------------------
--  DDL for Index SYS_C0023212
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARIMOATESTDB"."SYS_C0023212" ON "ARIMOATESTDB"."CATEGORI_JH" ("CATECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CATEGORI_JH
--------------------------------------------------------

  ALTER TABLE "ARIMOATESTDB"."CATEGORI_JH" ADD PRIMARY KEY ("CATECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ARIMOATESTDB"."CATEGORI_JH" MODIFY ("CATECODE" NOT NULL ENABLE);
  ALTER TABLE "ARIMOATESTDB"."CATEGORI_JH" MODIFY ("CATENAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CATEGORI_JH
--------------------------------------------------------

  ALTER TABLE "ARIMOATESTDB"."CATEGORI_JH" ADD FOREIGN KEY ("CATECODEREF")
	  REFERENCES "ARIMOATESTDB"."CATEGORI_JH" ("CATECODE") ENABLE;
